### ISSUE TITLE
Define column widths on both Col and TableList component

### ISSUE THREAD

**Issue by Jepzter** [johnfercher/maroto#129]
**Is your feature request related to a problem? Please describe.**
I think you should have the possibility to change the width of the columns, especially in the TableList component. When you many column in the list, some may just contain one character and some might have a lot of information. It makes no sense that the column with one character should take as big of a space like the one with a lot of information and get cropped to a new line. Instead we should be able to manage this a bit to free up more space for the ones needed.

**Describe the solution you'd like**
Maroto should be able to specify not only height, but also width like so: 
`m.Col(20,19, func() {})` 

The TableList should maybe have a slice of float64 in the TableProps defining each columns width. 

**Describe alternatives you've considered**
Add additional but optional extra parameter / rewrite to a struct for the Col component to take in.
Add extra struct field called ColSizes that is of type []float64 that holds the size of the columns.

**Comment by Jepzter** [comment]
@johnfercher do you think this one is hard to solve?

**Comment by johnferchermeli** [comment]
I think this is a very good feature, but we have to analyze the possibilities first. These are my thoughts about it.

1.  I don't give the possibility to define the width of each col. If the user set the width with the pixel value, what happens if the sum of the cols pass the useful area of the PDF?
2. Given that maroto ins inspired in Bootstrap, I think we should give the possibility to set a value between 0 or 12 to each col (as Bootstrap does), and if sum of cols pass 12 in one Row I think we should apply the same logic that Bootstrap apply.
3. I don't think this is too difficulty.

**Comment by Jepzter** [comment]
My first thought was to work with percentage to handle the amount of columns not overriding page width. But I think the idea of working with a 12-col grid is better, as it also is in line with bootstrap.

I will try implement this and ask you for help if I get stuck on something. 😄

**Comment by johnferchermeli** [comment]
Nice, it must be a Col feature. But you will need to change the code above (GetWidthPerCol).
