### ISSUE TITLE
add image to content

### ISSUE THREAD

**Issue by batara666** [johnfercher/maroto#158]
how to add image to content ? (contents type are `[][]string`)

**Comment by monakhovm** [comment]
Base64?

**Comment by johnfercher** [comment]
Hello, this will be easy to do in maroto V2. Since you can iterate through a collection of data and build a structure of rows/cols applying all kind of customizations. Please refer to [maroto v2](https://maroto.io/#/v2/examples/billing?id=billing) to see how this can be done. 

Btw, I will keep this issue alive until maroto v2 reaches a stable version.

**Comment by johnfercher** [comment]
I have an update on this. I added a new way to compute tables. The new can be seen here: https://maroto.io/#/v2/features/list?id=list
