### ISSUE TITLE
Improve TableList GridSizes handling to avoid panic

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#178]
**Describe the bug**

Sometimes when we are developing using TableList and do not pass a correct quantity of grid sizes in the pros the maroto calls a panic.

**Expected behavior**

Maroto must validate if the combination is valid and avoid the panic.

**Comment by johnfercher** [comment]
Hello, this will be easy to do in maroto V2. Since you can iterate through a collection of data and build a structure of rows/cols applying all kind of customizations. Please refer to [maroto v2](https://maroto.io/#/v2/examples/billing?id=billing) to see how this can be done. 

Btw, I will keep this issue alive until maroto v2 reaches a stable version.

**Comment by johnfercher** [comment]
I have an update on this. I added a new way to compute tables. The new can be seen here: https://maroto.io/#/v2/features/list?id=list

**Comment by johnfercher** [comment]
This new way there is no way to occur a panic inside table list
