### ISSUE TITLE
creating PDF documents using existing PDFs

### ISSUE THREAD

**Issue by annaitzhaki** [johnfercher/maroto#197]
**Is your feature request related to a problem? Please describe.**
I would like to open an existing PDF and modify it

**Describe the solution you'd like**
Open an existing pdf file and modify id: add text, image, extra page

**Describe alternatives you've considered**
I saw this library: https://github.com/signintech/pdft
didn't try it.

**Additional context**

**Comment by SahaPratik6267** [comment]
I am also looking for this feature. currently I am working with a pdf generation where first page is some info and second page will have the invoice. now invoice can be image or pdf. for image I already did it but now I need to do for pdf option. In short what I would like to do is the user input a pdf and I will take each page as a image and add it in the actual pdf. The actual pdf has header option so I would not change that.

Let me know if you have any plan to add it. Otherwise it will be a problem for me.

**Comment by johnfercher** [comment]
@F-Amaral easy to solve with the merge pdfs used in parallel generation

**Comment by johnfercher** [comment]
Added this on `v2.0.0-alpha.19` (https://maroto.io/#/v2/features/addpdf?id=add-pdf)
