### ISSUE TITLE
A way to truncate text?

### ISSUE THREAD

**Issue by frederikhors** [johnfercher/maroto#204]
Is there a way to truncate text such as [Tailwind's one](https://tailwindcss.com/docs/text-overflow#truncate)?

**Comment by johnfercher** [comment]
There is no way to truncate text currently. But I think this is a good feature, I will add to the feature queue.

**Comment by johnfercher** [comment]
**Is your feature request related to a problem? Please describe.**

Maroto doesn't provide a way to truncate text.

**Describe the solution you'd like**

Implement an extensible way to deal with text extrapolation in rows. This is important because we would implement text wrap in the future as asked in #202.

**Describe alternatives you've considered**

Change the [Text.Add](https://github.com/johnfercher/maroto/blob/303a31388a121bed8f8fb2749265cac34d4f2625/internal/text.go#L33) to compute text extrapolation and change final characters to `...`.

**Additional context**

* Use somekind of enum to differentiate wrap from trucation.

**Comment by frederikhors** [comment]
Any news on this @johnfercher? 🙏

**Comment by mxsg** [comment]
I am also interested in this feature and would be open to implementing it, so I would like to get a better understanding of what you were envisioning with it.

> Implement an extensible way to deal with text extrapolation in rows. This is important because we would implement text wrap in the future as asked in #202.

@johnfercher Not sure what you mean by "text extrapolation" in general. In the meantime, text wrapping is now supported and controlled by the `Extrapolate` flag on `props.Text`, which allows the text to overflow its cell instead of wrapping?

My intuitive idea for this would be to add another flag like `Truncate` to `props.Text`, and in case it is set, to find the longest sequence of the text with the suffix `...` that still fits the cell (or alternatively, the actual ellipsis character `…`; not sure you can assume it exists in all relevant fonts, though). Not entirely sure what the behavior should be when combining those flags.

Of course there is some complexity in getting this right for general unicode text, at least you would want to split the input only along grapheme cluster boundaries. I don't know whether there is already a way of finding those with the dependencies of this library, but otherwise, there are libraries like [uniseg](https://github.com/rivo/uniseg). What do you think?

**Comment by johnfercher** [comment]
Added a new strategy to break line by using dash instead of space. Added in `v2.0.0-alpha.22` (https://maroto.io/#/v2/features/customfont?id=custom-font). This feature with automatic height calculation will made trucante uncessary in future.
