### ISSUE TITLE
Why a dot is printed instead of `→`?

### ISSUE THREAD

**Issue by frederikhors** [johnfercher/maroto#205]
**Describe the bug**

I'm trying to insert this character `→` in pdf with `m.Text()` with no luck. A `.` is printed instead.

Why?

**Additional details:**
 - OS: Windows 10
 - github.com/johnfercher/maroto v0.36.1

**Comment by johnfercher** [comment]
Are you using an [UTF8 font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font)? If not, maybe this caracter only be supported in utf8 fonts.

**Comment by frederikhors** [comment]
I'm using it on Windows 10. I'm using all the default settings, all the default code with no methods.

I think it should already work just fine, with no need to add any special fonts. Am I right?

**Comment by johnfercher** [comment]
As maroto uses [gofpdf](https://github.com/jung-kurt/gofpdf), the project is limited in some aspects of gofpdf. The gofpdf only implements the code pages **cp1250** and **cp1252** as you can see [here](https://github.com/jung-kurt/gofpdf/blob/master/embedded.go).  Looking for the unicode of [→](https://unicode.scarfboy.com/?s=%E2%86%92), I found the code `U+2192` which gofpdf doesn't have support. Neither all fonts support this unicode, looking for a font which may support this unicode, I found [theses fonts](https://en.wikipedia.org/wiki/Unicode_font) and [arial-unicode-ms.ttf](https://www.fileformat.info/info/unicode/font/arial_unicode_ms/blockview.htm?block=arrows) support all those arrow characters as you can see bellow.

## Result 
<img width="1027" alt="Captura de Tela 2022-05-08 às 12 08 26" src="https://user-images.githubusercontent.com/4752636/167302595-1845efa9-4788-443e-92ae-cebf1314446a.png">

## Code Snippet
```golang
package main

import (
	"fmt"
	"github.com/johnfercher/maroto/pkg/props"
	"os"
	"time"

	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
)

func main() {
	begin := time.Now()
	m := pdf.NewMaroto(consts.Portrait, consts.Letter)
	m.SetBorder(true)

	m.AddUTF8Font("CustomArial", consts.Normal, "internal/assets/fonts/arial-unicode-ms.ttf")
	m.AddUTF8Font("CustomArial", consts.Italic, "internal/assets/fonts/arial-unicode-ms.ttf")
	m.AddUTF8Font("CustomArial", consts.Bold, "internal/assets/fonts/arial-unicode-ms.ttf")
	m.AddUTF8Font("CustomArial", consts.BoldItalic, "internal/assets/fonts/arial-unicode-ms.ttf")
	m.SetDefaultFontFamily("CustomArial")

	m.Row(40, func() {
		m.Col(12, func() {
			m.Text("x → ∞", props.Text{
				Size: 20,
			})
		})
	})

	err := m.OutputFileAndClose("internal/examples/pdfs/textgrid.pdf")
	if err != nil {
		fmt.Println("Could not save PDF:", err)
		os.Exit(1)
	}

	end := time.Now()
	fmt.Println(end.Sub(begin))
}
```

Since this font have 23Mb I don't see as a good idea make maroto use this font as default because not every use case possible for maroto would need such special symbols. So, I think that the best way to proceed in this case is using the [UTF8 font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font) when needed.

**Comment by frederikhors** [comment]
Thank you very much.

What I do not understand (because of my ignorance) is why on, let's say Windows 10, I cannot say to `maroto` to use `Arial Unicode` if it can found on the OS (if it's installed) or not otherwise.

This is what I do not understand.

Can we do this?

**Comment by johnfercher** [comment]
Actually, all fonts built-in in maroto are exported as you can see in [gofpdf](https://github.com/jung-kurt/gofpdf/blob/master/embedded.go) code. There are mini copies of arial, courier and so on inside de code, when you say to maroto use arial, it's not using the Arial installed in your OS, unless your add the arial.ttf with the [AddUTF8Font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font).

**Comment by frederikhors** [comment]
Ok. This is the technical answer. But the logical one?
