### ISSUE TITLE
[FR] TableList: support for text style in individual cell

### ISSUE THREAD

**Issue by Vovan-VE** [johnfercher/maroto#215]
It would be great to apply extra `text.Style` for individual data cells in `TableList`.

Example table to produce with `TableList`:

| Col 1 | Col 2 |
| --- | --- |
| Foo | _custom cell style_ |
| Bar | **another style** |
| Baz | Nothing special here |

**Comment by johnfercher** [comment]
Hello, this will be easy to do in maroto V2. Since you can iterate through a collection of data and build a structure of rows/cols applying all kind of customizations. Please refer to [maroto v2](https://maroto.io/#/v2/examples/billing?id=billing) to see how this can be done. 

Btw, I will keep this issue alive until maroto v2 reaches a stable version.

**Comment by johnfercher** [comment]
I have an update on this. I added a new way to compute tables. The new can be seen here: https://maroto.io/#/v2/features/list?id=list
