### ISSUE TITLE
Centre table

### ISSUE THREAD

**Issue by DaniilGo** [johnfercher/maroto#246]
Hi!
Thank you for such useful library!
Is there any opportunity to adjust table on the centre of the page?
for example:
```
m.TableList(header, contents, props.TableList{
				HeaderProp: props.TableListContent{
					Size:      9,
					GridSizes: []uint{4, 2},
				},
				...
```
so the grid is 6 from 12 points and the table will appear on the centre of the page?

Thank you in advance!

**Comment by johnfercher** [comment]
Hello, this will be easy to do in maroto V2. Since you can iterate through a collection of data and build a structure of rows/cols applying all kind of customizations. Please refer to [maroto v2](https://maroto.io/#/v2/examples/billing?id=billing) to see how this can be done. 

Btw, I will keep this issue alive until maroto v2 reaches a stable version.

**Comment by johnfercher** [comment]
I have an update on this. I added a new way to compute tables. The new can be seen here: https://maroto.io/#/v2/features/list?id=list
