### ISSUE TITLE
WithMargins is missing bottom

### ISSUE THREAD

**Issue by oSethoum** [johnfercher/maroto#369]
WithMargings function in the config builder is missing `bottom` config
it should be 
`WithMragins(left float64, top float64, right float64, bottom float64) Builder`

**Comment by johnfercher** [comment]
I searched on gofpdf, I didn't find a way to customiza the bottom margin of the document. This is why I didn't add this option to the builder.

**Comment by cadoween** [comment]
hey, I'm facing this too! 

I'm just wondering if there's a way to maybe lower down the content of the footer a little bit? I saw the `MinBottomMargin` value being hardcoded so I've tried to lower down the value and the result was that the footer goes to the second page even though the first page isn't full yet.

Previously I used pure `gofpdf` with `SetFooterFunc`, but I think you have a specific reason why you didn't leverage that 🤔 .

**Comment by johnfercher** [comment]
I hardcoded `MinBottomMargin` as the same value as gofpdf.

**Comment by johnfercher** [comment]
I will have a deeper look to see what can be done.

**Comment by GreatGodApollo** [comment]
Out of curiosity, I took a look at `gofpf` and it seems like there is a way to override the bottom margin. The functionality is tied into setting the page break functionality as well: [`func (f *Fpdf) SetAutoPageBreak(auto bool, margin float64)`](https://pkg.go.dev/github.com/jung-kurt/gofpdf#Fpdf.SetAutoPageBreak). It may be worth adding this setting to the config/internally using it in order to override the bottom margin.

**Comment by johnfercher** [comment]
I will try this.
